### ISSUE TITLE
fix: FirebaseFirestoreAdminException: firestore/unknown: The service is temporarily unavailable. {error: {code: 503, message: The service is temporarily unavailable., status: UNAVAILABLE}} 

### ISSUE THREAD

**Issue by mafreud** [openci-org/openci_runner#107]
```
Unhandled exception:
FirebaseFirestoreAdminException: firestore/unknown: The service is temporarily unavailable. {error: {code: 503, message: The service is temporarily unavailable., status: UNAVAILABLE}} 
#0      validateResponse (package:_discoveryapis_commons/src/api_requester.dart:306:9)
<asynchronous suspension>
#1      ApiRequester.request (package:_discoveryapis_commons/src/api_requester.dart:72:16)
<asynchronous suspension>
#2      ProjectsDatabasesDocumentsResource.runQuery (package:firebaseapis/firestore/v1.dart:1881:23)
<asynchronous suspension>
#3      Query._get (package:dart_firebase_admin/src/google_cloud_firestore/reference.dart:1110:22)
<asynchronous suspension>
#4      RunnerCommand.run (package:openci_runner/src/features/runner/runner_command.dart:85:22)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      OpenciRunnerCommandRunner.runCommand (package:openci_runner/src/command_runner.dart:118:18)
<asynchronous suspension>
#7      OpenciRunnerCommandRunner.run (package:openci_runner/src/command_runner.dart:62:14)
<asynchronous suspension>
#8      main (file:///Users/admin/.pub-cache/hosted/pub.dev/openci_runner-0.6.0/bin/openci_runner.dart:6:24)
<asynchronous suspension>
```

**Comment by mafreud** [comment]
This is due to network disconnection.
